// Re-export from refactored tidal module for backward compatibility.
// All new code should import from "../services/tidal" directly.
export {
  loadCredentials,
  initTidalClient,
  getClient,
  getUserId,
  parseDuration,
  formatKey,
  mapTrackResource,
  resolveTrackMeta,
  buildIncludedMap,
  delay,
  fetchTracksByIds,
  searchArtists,
  searchTracks,
  getArtistTopTracks,
  getArtistAlbums,
  getAlbumTracks,
  getTrack,
  getSimilarTracks,
  getTrackRadio,
  getPlaylistTracks,
  getFavoriteTracks,
  createPlaylist,
  addTracksToPlaylist,
  type CreatePlaylistOptions,
} from "./tidal";
